"""Patch the HollowHull Unreal project so the Hollow Hull scripts can build into it.

The project itself must be created with Epic's launcher (New Project > Games >
Third Person > Blueprint): Unreal 5.7 templates pull in shared content packs
(input actions, mannequin) that only the launcher installs.

    python prepare_project.py --existing "C:/Projects/HollowHull/HollowHull.uproject" --repo "<hollow-hull folder>"

It enables the Python and Editor Scripting plugins, makes L_FloodedDeck the
startup map, and writes Content/Python/init_unreal.py. Unreal runs that file on
every editor start; it builds the level only when run_phase1.ps1 has left a
build request, so normal editor launches are untouched and the editor stays open.
Plain Python 3, no Unreal needed.
"""

import argparse
import json
import os
import re
import sys

PLUGINS = ["PythonScriptPlugin", "EditorScriptingUtilities"]
MAP = "/Game/HollowHull/Maps/L_FloodedDeck.L_FloodedDeck"

INIT_UNREAL = '''# Generated by hollow-hull tools/prepare_project.py - safe to delete.
# Builds L_FloodedDeck when run_phase1.ps1 leaves Saved/HollowHull/build_request.
import os
import runpy

import unreal

HH_REPO = r"{repo}"
_saved = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_saved_dir())
_request = os.path.join(_saved, "HollowHull", "build_request")
if os.path.exists(_request):
    os.remove(_request)
    os.environ["HH_REPO"] = HH_REPO
    unreal.log("[HH] build request found, running hh_setup.py from " + HH_REPO)
    runpy.run_path(os.path.join(HH_REPO, "unreal", "hh_setup.py"), run_name="__main__")
'''


def enable_plugins(uproject):
    with open(uproject, encoding="utf-8-sig") as f:
        data = json.load(f)
    plugins = data.setdefault("Plugins", [])
    for name in PLUGINS:
        entry = next((p for p in plugins if p.get("Name") == name), None)
        if entry:
            entry["Enabled"] = True
        else:
            plugins.append({"Name": name, "Enabled": True})
    with open(uproject, "w", encoding="utf-8") as f:
        json.dump(data, f, indent="\t")
    print(f"[HH] plugins enabled: {', '.join(PLUGINS)}")


def set_startup_map(project_dir):
    ini = os.path.join(project_dir, "Config", "DefaultEngine.ini")
    text = open(ini, encoding="utf-8-sig").read() if os.path.exists(ini) else ""
    section = "[/Script/EngineSettings.GameMapsSettings]"
    keys = {"EditorStartupMap": MAP, "GameDefaultMap": MAP}
    if section in text:
        start = text.index(section) + len(section)
        nxt = text.find("\n[", start)
        end = len(text) if nxt == -1 else nxt
        body = text[start:end]
        for k, v in keys.items():
            if re.search(rf"^{k}=", body, flags=re.M):
                body = re.sub(rf"^{k}=.*$", f"{k}={v}", body, flags=re.M)
            else:
                body = body.rstrip("\n") + f"\n{k}={v}\n"
        text = text[:start] + body + text[end:]
    else:
        text = text.rstrip("\n") + f"\n\n{section}\n" + "".join(f"{k}={v}\n" for k, v in keys.items())
    os.makedirs(os.path.dirname(ini), exist_ok=True)
    with open(ini, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[HH] startup map -> {MAP}")


def install_startup_hook(project_dir, repo):
    path = os.path.join(project_dir, "Content", "Python", "init_unreal.py")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(INIT_UNREAL.format(repo=os.path.abspath(repo)))
    print(f"[HH] startup hook -> {path}")


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--existing", required=True, help="path to the launcher-made .uproject")
    ap.add_argument("--repo", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    help="the hollow-hull folder (default: the one this script is in)")
    args = ap.parse_args(argv)
    if not os.path.isfile(args.existing):
        raise SystemExit(f"no project at {args.existing}; create it in the Unreal launcher first")
    project_dir = os.path.dirname(os.path.abspath(args.existing))
    enable_plugins(args.existing)
    set_startup_map(project_dir)
    install_startup_hook(project_dir, args.repo)
    print(f"[HH] project ready: {os.path.abspath(args.existing)}")


if __name__ == "__main__":
    main(sys.argv[1:])
